name: Deploy-Pre

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true

    - name: Switch to pre branch
      run: |
        cd docs
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        git fetch
        git checkout bowen/v1.16
        git status

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: |
        pnpm docs:build

    - name: Push gh-pages-pre
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vuepress/dist
        publish_branch: gh-pages-pre

    - name: Deploy-Pre
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        allenvs: true
        script: |
          cd /data/wwwroot/pre.goravel.dev/ && git pull origin gh-pages-pre
          